fix: continue and status

diff --git a/.github/workflows/test_integration.yml b/.github/workflows/test_integration.yml
--- a/.github/workflows/test_integration.yml
+++ b/.github/workflows/test_integration.yml
@@ -66,13 +66,14 @@ jobs:
           detached: true
       - name: Setup operator environment
         id: setup-op-0
+        continue-on-error: true
         uses: charmed-kubernetes/actions-operator@main
         with:
           provider: ${{ matrix.action-operator.cloud }}
           channel: ${{ matrix.action-operator.cloud-channel }}
           juju-channel: ${{ matrix.action-operator.juju }}
           lxd-channel: ${{ matrix.action-operator.lxd-channel }}
-      - name: Setup operator environment retry 1
+      - name: Setup operator environment (retry 1)
         id: setup-op-1
         continue-on-error: true
         if: steps.setup-op-0.outcome == 'failure'
@@ -82,16 +83,24 @@ jobs:
           channel: ${{ matrix.action-operator.cloud-channel }}
           juju-channel: ${{ matrix.action-operator.juju }}
           lxd-channel: ${{ matrix.action-operator.lxd-channel }}
-      - name: Setup operator environment retry 2
+      - name: Setup operator environment (retry 2)
         id: setup-op-2
         continue-on-error: true
-        if: steps.setup-op-0.outcome == 'failure'
+        if: steps.setup-op-1.outcome == 'failure'
         uses: charmed-kubernetes/actions-operator@main
         with:
           provider: ${{ matrix.action-operator.cloud }}
           channel: ${{ matrix.action-operator.cloud-channel }}
           juju-channel: ${{ matrix.action-operator.juju }}
           lxd-channel: ${{ matrix.action-operator.lxd-channel }}
+      - name: Setup operator environment (set status)              # set the workflow status if command failed
+        if: always()
+        run: |
+          if ${{ steps.setup-op-0.outcome == 'success' || steps.setup-op-1.outcome == 'success' || steps.setup-op-2.outcome=='success' }}; then
+             echo "Setup operator environment succeeded"
+          else
+             exit 1
+          fi
       - name: Print logs
         run: |
           sudo journalctl -u snap.juju-db.mongod
